### ISSUE TITLE
No worky :(

### ISSUE THREAD

**Issue by jchannon** [richorama/nuget-tree#1]
I have node 7.6.0

Followed your instructions to install.

Went to folder with project.lock.json and ran `nuget-tree` but get `env: node\r: no such file or directory`

Any ideas?

**Comment by richorama** [comment]
Thanks for the feedback @jchannon 

Which OS are you on?

**Comment by jchannon** [comment]
OSX

**Comment by richorama** [comment]
Ah, after a bit of googling it looks like a (unix/windows) line ending problem.

I'll fix and test later today.

**Comment by jchannon** [comment]
👍

**Comment by richorama** [comment]
I have switched the line endings and published version 1.0.7.

Would you mind updating and trying again?

```
npm uninstall nuget-tree -g
npm install nuget-tree -g
```

**Comment by jchannon** [comment]
Done, still says 1.0.6

**Comment by richorama** [comment]
gah, I think I failed to publish.

Sorry, try again. I can see 1.0.7 is there now https://www.npmjs.com/package/nuget-tree

**Comment by jchannon** [comment]
There now! :)

On a dotnetcore project I now get "Cannot find 'packages' directory. Have
you run 'nuget restore'?" I won't get a packages directory for a dotnetcore
project

**Comment by richorama** [comment]
Ah ha, I've not got to that yet (I've not been keeping up with the latest in .NET core).

Am I correct in thinking the packages are stored here: `C:\Users\[User]\.nuget\packages`?

**Comment by richorama** [comment]
BTW, `project.lock.json` is supported, although I'm not sure if that's still used?

**Comment by jchannon** [comment]
I'm testing against a directory with project.lock.json in it and get the
pacakges warning.

I think thats correct for Windows. For OSX and I assume Linux
its ~/.nuget/packages

**Comment by jchannon** [comment]
Interesting if i create an empty packages folder it works!

**Comment by richorama** [comment]
ah, I've fixed that now (v 1.0.8).

I started off only looking at the traditional `packages.config`, which would require the packages directory for me to read the dependencies from the package.

**Comment by jchannon** [comment]
Understood! Good job. Thanks!

**Comment by richorama** [comment]
Thanks for your feedback :¬)

**Comment by jchannon** [comment]
Cheers for quick turn around
